name: Bdd MYSQL Quest 1

on:
    pull_request:
        types: [opened, synchronize, reopened, ready_for_review]
        paths:
          - "src/Bdd/Mysql/Quest-1/**"

jobs:
    check-files:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
                if: github.event_name == 'pull_request'

            -   name: Get changed files
                id: changed-files
                uses: tj-actions/changed-files@v35

            -   name: List all changed files
                run: |
                    excluded_files="src/Bdd/Mysql/Quest-1/quest-1_1|2.sql"

                    invalid_files=()

                    for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
                        if [[ ! $file =~ $excluded_files ]]; then
                            invalid_files+=("$file")
                        fi
                    done

                    if [[ ${#invalid_files[@]} -ne 0 ]]; then
                        echo "Des fichiers autres que ceux attendus ont été ajoutés ou modifiés dans la pull request :"

                        for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
                            if [[ ! $file =~ $excluded_files ]]; then
                                echo "$file modifié"
                            fi
                        done

                        exit 1
                    fi
    validation:
        runs-on: ubuntu-latest
        needs: check-files

        env:
            resource-dump: ./resources/Bdd/Mysql/quest1.sql
            working-directory: ./src/Bdd/Mysql/Quest-1
            db_name: wild_db_quest
            db_password: db_password
        services:
            mysql:
                image: mysql:8.0.27
                env:
                    MYSQL_DATABASE: ${{ env.db_name }}
                    MYSQL_ROOT_PASSWORD: ${{ env.db_password }}
                ports:
                    - 3306:3306
                options: >-
                    --health-cmd="mysqladmin ping"
                    --health-interval=10s
                    --health-timeout=5s
                    --health-retries=3
        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Generate Correction
                run: |
                    mysql --host=127.0.0.1 --user=root --password=${{ env.db_password }} -e "${{ secrets.BDD_MYSQL_QUEST_1_1_RESULT }}" ${{ env.db_name }} > correction.txt
                    mysql --host=127.0.0.1 --user=root --password=${{ env.db_password }} ${{ env.db_name }} < ./resources/Bdd/Mysql/quest1.sql >> correction.txt
                    mysql --host=127.0.0.1 --user=root --password=${{ env.db_password }} -e "${{ secrets.BDD_MYSQL_QUEST_1_2_RESULT }}" ${{ env.db_name }} >> correction.txt

            -   name: Generate Answer
                run: |
                    mysql --host=127.0.0.1 --user=root --password=${{ env.db_password }} ${{ env.db_name }} < ${{ env.working-directory }}/quest-1_1.sql > answer.txt
                    mysql --host=127.0.0.1 --user=root --password=${{ env.db_password }} ${{ env.db_name }} < ./resources/Bdd/Mysql/quest1.sql >> answer.txt
                    mysql --host=127.0.0.1 --user=root --password=${{ env.db_password }} ${{ env.db_name }} < ${{ env.working-directory }}/quest-1_2.sql >> answer.txt

            -   name: Validate Answer
                run: diff correction.txt answer.txt
