name: Bdd MYSQL Quest 6

on:
    push:
        paths:
          - "src/Bdd/Mysql/Quest-6/**"
    pull_request:
        types: [opened, synchronize, reopened, ready_for_review]
        paths:
          - "src/Bdd/Mysql/Quest-6/**"

jobs:
    check-files:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
                if: github.event_name != 'pull_request'
                with:
                    fetch-depth: 0

            -   uses: actions/checkout@v3
                if: github.event_name == 'pull_request'

            -   name: Get changed files
                id: changed-files
                uses: tj-actions/changed-files@v35

            -   name: List all changed files
                run: |
                    for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
                        echo "$file was changed"
                    done

    validation:
        runs-on: ubuntu-latest
        needs: check-files

        env:
            resource-dump: ./resources/Bdd/Mysql/dump_quete_519_finie.sql
            working-directory: ./src/Bdd/Mysql/Quest-6
            db_name: wild_db_quest
            db_password: db_password
        services:
            mysql:
                image: mysql:8.0.27
                env:
                    MYSQL_DATABASE: ${{ env.db_name }}
                    MYSQL_ROOT_PASSWORD: ${{ env.db_password }}
                ports:
                    - 3306:3306
                options: >-
                    --health-cmd="mysqladmin ping"
                    --health-interval=10s
                    --health-timeout=5s
                    --health-retries=3
        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Recherche des fichiers non autorisés dans la PR
                if: github.event_name == 'pull_request'
                run: |
                    files=$(git diff --name-only HEAD $(git merge-base HEAD ${{ github.event.pull_request.base.sha }}))
                    excluded_files='src/bdd/mysql/quest-06/quest-6.sql'

                    invalid_files=()

                    for file in $files; do
                        if [[ ! $file =~ $excluded_files ]]; then
                            invalid_files+=("$file")
                        fi
                    done

                    if [[ ${#invalid_files[@]} -ne 0 ]]; then
                        echo "Des fichiers autres que src/bdd/mysql/quest-06/quest-6.sql ont été ajoutés ou modifiés dans la pull request :"
                        printf '%s\n' "${invalid_files[@]}"
                        exit 1
                    fi

            -   name: Recherche des fichiers non autorisés dans le Commit
                if: github.event_name != 'pull_request'
                run: |
                    set -e
                    non_authorized_files=($(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -qvE '^src/bdd/mysql/quest-06/quest-6.sql$' || true))
                    if [ ${#non_authorized_files[@]} -ne 0 ]; then
                        echo "ERREUR : les modifications doivent être apportées uniquement à 'src/bdd/mysql/quest-06/quest-6.sql'"
                        for file in "${non_authorized_files[@]}"; do
                            echo "- $file"
                        done
                        exit 1
                    fi

            -   name: Prepare db
                run: |
                    mysql --host=127.0.0.1 --user=root --password=${{ env.db_password }} ${{ env.db_name }} < ${{ env.resource-dump }}

            -   name: Generate Correction
                run: |
                    mysql --host=127.0.0.1 --user=root --password=${{ env.db_password }} -e "${{ secrets.BDD_MYSQL_QUEST_6_RESULT }}" ${{ env.db_name }} > correction.txt

            -   name: Generate Answer
                run: |
                    mysql --host=127.0.0.1 --user=root --password=${{ env.db_password }} ${{ env.db_name }} < ${{ env.working-directory }}/quest-6.sql > answer.txt

            -   name: Validate Answer
                run: |
                    diff correction.txt answer.txt
