name: Bdd MYSQL Quest 5

on:
    push:
        paths:
          - "src/bdd/mysql/quest-05/**"
    pull_request:
        types: [opened, synchronize, reopened, ready_for_review]
        paths:
          - "src/bdd/mysql/quest-05/**"

jobs:
    check-files:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
                with:
                    ref: ${{ github.head_ref }}

            -   name: Recherche des fichiers non autorisés dans la PR
                if: github.event_name == 'pull_request'
                run: |
                    set -e
                    non_authorized_files=($(git diff --name-only HEAD $(echo ${{ github.event.pull_request.base.sha }}) | grep -v 'src/bdd/mysql/quest-05/quest-5.sql' || true))
                    if [ ${#non_authorized_files[@]} -ne 0 ]; then
                        echo "La pull request contient des fichiers non autorisés :"
                        for file in "${non_authorized_files[@]}"; do
                            echo "- $file"
                        done
                        exit 1
                    fi

            -   name: Recherche des fichiers non autorisés dans le Commit
                if: github.event_name != 'pull_request'
                run: |
                    set -e
                    non_authorized_files=($(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -qvE '^src/bdd/mysql/quest-05/quest-5.sql$' || true))
                    if [ ${#non_authorized_files[@]} -ne 0 ]; then
                        echo "ERREUR : les modifications doivent être apportées uniquement à 'src/bdd/mysql/quest-05/quest-5.sql'"
                        for file in "${non_authorized_files[@]}"; do
                            echo "- $file"
                        done
                        exit 1
                    fi
    validation:
        runs-on: ubuntu-latest

        env:
            resource-dump: ./Resource/bdd/mysql/dump_quete_519_finie.sql
            working-directory: ./src/bdd/mysql/quest-05
            db_name: wild_db_quest
            db_password: db_password
        services:
            mysql:
                image: mysql:8.0.27
                env:
                    MYSQL_DATABASE: ${{ env.db_name }}
                    MYSQL_ROOT_PASSWORD: ${{ env.db_password }}
                ports:
                    - 3306:3306
                options: >-
                    --health-cmd="mysqladmin ping"
                    --health-interval=10s
                    --health-timeout=5s
                    --health-retries=3
        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Prepare db
                run: |
                    mysql --host=127.0.0.1 --user=root --password=${{ env.db_password }} ${{ env.db_name }} < ${{ env.resource-dump }}

            -   name: Generate Correction
                run: |
                    mysql --host=127.0.0.1 --user=root --password=${{ env.db_password }} -e "${{ secrets.BDD_MYSQL_QUEST_5_RESULT }}" ${{ env.db_name }} > correction.txt

            -   name: Generate Answer
                run: |
                    mysql --host=127.0.0.1 --user=root --password=${{ env.db_password }} ${{ env.db_name }} < ${{ env.working-directory }}/quest-5.sql > answer.txt

            -   name: Validate Answer
                run: |
                    diff correction.txt answer.txt
