name: Bdd MYSQL Quest 5

on:
    push:
        paths:
          - "src/bdd/mysql/quest-05/**"
    pull_request:
        types: [opened, synchronize, reopened, ready_for_review]
        paths:
          - "src/bdd/mysql/quest-05/**"

jobs:
    validation:
        runs-on: ubuntu-latest

        env:
            resource-dump: ./Resource/bdd/mysql/dump_quete_519_finie.sql
            working-directory: ./src/bdd/mysql/quest-05
            db_name: wild_db_quest
            db_password: db_password
        services:
            mysql:
                image: mysql:8.0.27
                env:
                    MYSQL_DATABASE: ${{ env.db_name }}
                    MYSQL_ROOT_PASSWORD: ${{ env.db_password }}
                ports:
                    - 3306:3306
                options: >-
                    --health-cmd="mysqladmin ping"
                    --health-interval=10s
                    --health-timeout=5s
                    --health-retries=3
        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Prepare db
                run: |
                    mysql --host=127.0.0.1 --user=root --password=${{ env.db_password }} ${{ env.db_name }} < ${{ env.resource-dump }}

            -   name: Generate Correction
                run: |
                    echo "${{ vars.BDD_MYSQL_QUEST_5_RESULT }}" > correction.sql \
                    && mysql --host=127.0.0.1 --user=root --password=${{ env.db_password }} ${{ env.db_name }} < correction.sql > correction.txt

            -   name: Generate Answer
                run: |
                    mysql --host=127.0.0.1 --user=root --password=${{ env.db_password }} ${{ env.db_name }} < ${{ env.working-directory }}/quest-5.sql > answer.txt

            -   name: Validate Answer
                run: |
                    diff correction.txt answer.txt
