name: JS POO Ex00

on:
    pull_request:
        types: [opened, synchronize, reopened, ready_for_review]
        paths:
          - "src/JS/POO/Ex00/**"

jobs:
    check-files:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3

            -   name: Get changed files
                id: changed-files
                uses: tj-actions/changed-files@v35

            -   name: List all changed files
                run: |
                    excluded_files="src/JS/POO/Ex00/Tyrion.cjs"

                    invalid_files=()

                    for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
                        if [[ ! $file =~ $excluded_files ]]; then
                            invalid_files+=("$file")
                        fi
                    done

                    if [[ ${#invalid_files[@]} -ne 0 ]]; then
                        echo "Des fichiers autres que `src/JS/POO/Ex00/Tyrion.cjs` ont été ajoutés ou modifiés dans la pull request :"

                        for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
                            if [[ ! $file =~ $excluded_files ]]; then
                                echo "$file modifié"
                            fi
                        done

                        exit 1
                    fi

            -   name: Install dependencies
                id: dependencies-cache
                run: npm install

            -   name: Cache dependencies
                id: cache
                uses: actions/cache@v3
                with:
                    path: ./node_modules
                    key: ${{ runner.os }}-${{ env.MODULE_CACHE_NAME }}-${{ hashFiles('**/package-lock.json') }}

    lint:
        runs-on: ubuntu-latest
        needs: check-files
        strategy:
            fail-fast: false
        steps:
            -   uses: actions/checkout@v3
                with:
                    ref: ${{ github.head_ref }}

            -   name: Cache dependencies
                id: cache-nextjob
                uses: actions/cache@v3
                with:
                    path: ./node_modules
                    key: ${{ runner.os }}-${{ env.MODULE_CACHE_NAME }}-${{ hashFiles('**/package-lock.json') }}

            -   name: Install dependencies
                if: steps.cache-nextjob.outputs.cache-hit != 'true'
                run: npm install

            -   name: Run linter
                run: npm run lint

    jest:
        runs-on: ubuntu-latest
        needs: check-files
        strategy:
            fail-fast: false
        steps:
            -   uses: actions/checkout@v3
                with:
                    ref: ${{ github.head_ref }}

            -   name: Cache dependencies
                id: cache-nextjob
                uses: actions/cache@v3
                with:
                    path: ./node_modules
                    key: ${{ runner.os }}-${{ env.MODULE_CACHE_NAME }}-${{ hashFiles('**/package-lock.json') }}

            -   name: Install dependencies
                if: steps.cache-nextjob.outputs.cache-hit != 'true'
                run: npm install

            -   name: Run Tests
                run: npm run test -- JS/POO/Ex00/Tyrion.spec.js
